// Package emit produces Go source files from a parsed schema.ModelSchema.
//
// Each emitter writes one file per entity into the destination package.
// The emitter is *not* gofmt-aware on its own — call gofmt on output, or
// rely on `go build` accepting it. Tests verify that output compiles.
package emit

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"

	"github.com/dataceen/client-go/tools/codegen/internal/schema"
)

// FileHeader is the standard banner that goes on top of every generated file.
func FileHeader(typeName, packageName string) string {
	return fmt.Sprintf(`// Code generated by tools/codegen. DO NOT EDIT.
// Regenerate via: go run ./tools/codegen/cmd emit %s
// Source: Dataceen introspection schema.

package %s

`, typeName, packageName)
}

// GoFieldName converts a server field name to its Go counterpart.
//
//	_id              -> MetaId
//	_documentVersion -> MetaDocumentVersion
//	_createdAt       -> MetaCreatedAt
//	CustomerId       -> CustomerId  (verbatim — Go field is exported)
//	IsActive         -> IsActive
//
// The underscore-prefixed form would shadow same-named business fields
// (Customer has both _createdAt and CreatedAt). Adding the Meta prefix is
// the cleanest way to avoid the collision while keeping wire-format intact
// (the JSON tag still uses the original name).
func GoFieldName(serverName string) string {
	if strings.HasPrefix(serverName, "_") {
		rest := serverName[1:]
		if rest == "" {
			return "Meta"
		}
		return "Meta" + capitalize(rest)
	}
	return capitalize(serverName)
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

// JSONTag returns the JSON struct-tag for a field, including ,omitempty when
// the field is optional. Required (non-null) fields always serialize.
func JSONTag(serverName string, nonNull bool) string {
	if nonNull {
		return fmt.Sprintf("`json:%q`", serverName)
	}
	return fmt.Sprintf("`json:\"%s,omitempty\"`", serverName)
}

// GoType returns the Go type for a field, considering optional vs required,
// list vs scalar, and the entity-emission set (so types not being emitted
// degrade to `any` instead of producing a build break).
//
// Rules:
//   - SCALAR  → mapped Go type (string, bool, int, ...)
//   - ENUM    → string (values are PascalCase enum literals on the wire)
//   - OBJECT/INPUT_OBJECT → ConvertedTypeName
//   - LIST    → []<element-type>
//   - Optional non-list OBJECT → *<type> so callers can distinguish absent.
//   - If baseType is not in `emitting`, fall back to `any`.
func GoType(field schema.FieldRef, scalars map[string]string, emitting map[string]bool) string {
	base := goBase(field, scalars, emitting)

	if field.IsList {
		return "[]" + base
	}
	if !field.NonNull && (field.BaseKind == "OBJECT" || field.BaseKind == "INPUT_OBJECT") &&
		emitting[field.BaseType] {
		return "*" + base
	}
	return base
}

func goBase(field schema.FieldRef, scalars map[string]string, emitting map[string]bool) string {
	switch field.BaseKind {
	case "SCALAR":
		if g, ok := scalars[field.BaseType]; ok {
			return g
		}
		return "any"
	case "ENUM":
		return "string"
	case "OBJECT", "INPUT_OBJECT":
		if emitting[field.BaseType] {
			return field.BaseType
		}
		return "any"
	default:
		return "any"
	}
}

// FormatGo runs gofmt on the source. Returns the formatted source on success,
// or the original source plus an error so the caller can still write a
// best-effort file for debugging.
func FormatGo(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return src, fmt.Errorf("gofmt: %w", err)
	}
	return string(out), nil
}
