// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: dataceenevent.proto

package dataceenevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartMode int32

const (
	StartMode_POSITION_BEGINNING StartMode = 0
	StartMode_POSITION_END       StartMode = 1
	StartMode_POSITION_EXACT     StartMode = 2
	StartMode_POSITION_TIME      StartMode = 3
	StartMode_BASELOAD           StartMode = 4
)

// Enum value maps for StartMode.
var (
	StartMode_name = map[int32]string{
		0: "POSITION_BEGINNING",
		1: "POSITION_END",
		2: "POSITION_EXACT",
		3: "POSITION_TIME",
		4: "BASELOAD",
	}
	StartMode_value = map[string]int32{
		"POSITION_BEGINNING": 0,
		"POSITION_END":       1,
		"POSITION_EXACT":     2,
		"POSITION_TIME":      3,
		"BASELOAD":           4,
	}
)

func (x StartMode) Enum() *StartMode {
	p := new(StartMode)
	*p = x
	return p
}

func (x StartMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dataceenevent_proto_enumTypes[0].Descriptor()
}

func (StartMode) Type() protoreflect.EnumType {
	return &file_dataceenevent_proto_enumTypes[0]
}

func (x StartMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartMode.Descriptor instead.
func (StartMode) EnumDescriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_NORMAL    MessageType = 0
	MessageType_KEEPALIVE MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "NORMAL",
		1: "KEEPALIVE",
	}
	MessageType_value = map[string]int32{
		"NORMAL":    0,
		"KEEPALIVE": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataceenevent_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_dataceenevent_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_SUBSCRIPTION_EVENT       EventType = 0
	EventType_BASELOAD_EVENT           EventType = 1
	EventType_BASELOAD_STEP_1          EventType = 2
	EventType_BASELOAD_STEP_1_ALL      EventType = 3
	EventType_BASELOAD_END             EventType = 4
	EventType_POSITION_AT_START_PASSED EventType = 5
	EventType_CONNECTION_LOST          EventType = 6
	EventType_CONNECTION_RECONNECTED   EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "SUBSCRIPTION_EVENT",
		1: "BASELOAD_EVENT",
		2: "BASELOAD_STEP_1",
		3: "BASELOAD_STEP_1_ALL",
		4: "BASELOAD_END",
		5: "POSITION_AT_START_PASSED",
		6: "CONNECTION_LOST",
		7: "CONNECTION_RECONNECTED",
	}
	EventType_value = map[string]int32{
		"SUBSCRIPTION_EVENT":       0,
		"BASELOAD_EVENT":           1,
		"BASELOAD_STEP_1":          2,
		"BASELOAD_STEP_1_ALL":      3,
		"BASELOAD_END":             4,
		"POSITION_AT_START_PASSED": 5,
		"CONNECTION_LOST":          6,
		"CONNECTION_RECONNECTED":   7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataceenevent_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_dataceenevent_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{2}
}

type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	OperationType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataceenevent_proto_enumTypes[3].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_dataceenevent_proto_enumTypes[3]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{3}
}

type ObjectType int32

const (
	ObjectType_NODE         ObjectType = 0
	ObjectType_RELATIONSHIP ObjectType = 1
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "NODE",
		1: "RELATIONSHIP",
	}
	ObjectType_value = map[string]int32{
		"NODE":         0,
		"RELATIONSHIP": 1,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataceenevent_proto_enumTypes[4].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_dataceenevent_proto_enumTypes[4]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{4}
}

type SubscriptionRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Domain                     string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Model                      string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Scope                      string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Baseloadtopics             []string               `protobuf:"bytes,4,rep,name=baseloadtopics,proto3" json:"baseloadtopics,omitempty"`
	Topics                     []string               `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`
	Ids                        []string               `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
	Startmode                  StartMode              `protobuf:"varint,7,opt,name=startmode,proto3,enum=dataceen.StartMode" json:"startmode,omitempty"`
	Position                   string                 `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	Starttime                  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Includedelta               bool                   `protobuf:"varint,10,opt,name=includedelta,proto3" json:"includedelta,omitempty"`
	Includecomplete            bool                   `protobuf:"varint,11,opt,name=includecomplete,proto3" json:"includecomplete,omitempty"`
	Baseloadcontinueobjecttype string                 `protobuf:"bytes,12,opt,name=baseloadcontinueobjecttype,proto3" json:"baseloadcontinueobjecttype,omitempty"`
	Positionbeforebaseload     string                 `protobuf:"bytes,13,opt,name=positionbeforebaseload,proto3" json:"positionbeforebaseload,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_dataceenevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataceenevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SubscriptionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SubscriptionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SubscriptionRequest) GetBaseloadtopics() []string {
	if x != nil {
		return x.Baseloadtopics
	}
	return nil
}

func (x *SubscriptionRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubscriptionRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SubscriptionRequest) GetStartmode() StartMode {
	if x != nil {
		return x.Startmode
	}
	return StartMode_POSITION_BEGINNING
}

func (x *SubscriptionRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *SubscriptionRequest) GetStarttime() *timestamppb.Timestamp {
	if x != nil {
		return x.Starttime
	}
	return nil
}

func (x *SubscriptionRequest) GetIncludedelta() bool {
	if x != nil {
		return x.Includedelta
	}
	return false
}

func (x *SubscriptionRequest) GetIncludecomplete() bool {
	if x != nil {
		return x.Includecomplete
	}
	return false
}

func (x *SubscriptionRequest) GetBaseloadcontinueobjecttype() string {
	if x != nil {
		return x.Baseloadcontinueobjecttype
	}
	return ""
}

func (x *SubscriptionRequest) GetPositionbeforebaseload() string {
	if x != nil {
		return x.Positionbeforebaseload
	}
	return ""
}

type EventData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Messagetype            MessageType            `protobuf:"varint,1,opt,name=messagetype,proto3,enum=dataceen.MessageType" json:"messagetype,omitempty"`
	Eventtype              EventType              `protobuf:"varint,2,opt,name=eventtype,proto3,enum=dataceen.EventType" json:"eventtype,omitempty"`
	Position               string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Eventtime              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=eventtime,proto3" json:"eventtime,omitempty"`
	Objecttype             ObjectType             `protobuf:"varint,5,opt,name=objecttype,proto3,enum=dataceen.ObjectType" json:"objecttype,omitempty"`
	Operationtype          OperationType          `protobuf:"varint,6,opt,name=operationtype,proto3,enum=dataceen.OperationType" json:"operationtype,omitempty"`
	Clientid               string                 `protobuf:"bytes,7,opt,name=clientid,proto3" json:"clientid,omitempty"`
	Domain                 string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	Model                  string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Topic                  string                 `protobuf:"bytes,10,opt,name=topic,proto3" json:"topic,omitempty"`
	Id                     string                 `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	Fromid                 string                 `protobuf:"bytes,12,opt,name=fromid,proto3" json:"fromid,omitempty"`
	Toid                   string                 `protobuf:"bytes,13,opt,name=toid,proto3" json:"toid,omitempty"`
	Delta                  string                 `protobuf:"bytes,14,opt,name=delta,proto3" json:"delta,omitempty"`
	Complete               string                 `protobuf:"bytes,15,opt,name=complete,proto3" json:"complete,omitempty"`
	Positionbeforebaseload string                 `protobuf:"bytes,16,opt,name=positionbeforebaseload,proto3" json:"positionbeforebaseload,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_dataceenevent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_dataceenevent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_dataceenevent_proto_rawDescGZIP(), []int{1}
}

func (x *EventData) GetMessagetype() MessageType {
	if x != nil {
		return x.Messagetype
	}
	return MessageType_NORMAL
}

func (x *EventData) GetEventtype() EventType {
	if x != nil {
		return x.Eventtype
	}
	return EventType_SUBSCRIPTION_EVENT
}

func (x *EventData) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *EventData) GetEventtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Eventtime
	}
	return nil
}

func (x *EventData) GetObjecttype() ObjectType {
	if x != nil {
		return x.Objecttype
	}
	return ObjectType_NODE
}

func (x *EventData) GetOperationtype() OperationType {
	if x != nil {
		return x.Operationtype
	}
	return OperationType_CREATE
}

func (x *EventData) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

func (x *EventData) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EventData) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EventData) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventData) GetFromid() string {
	if x != nil {
		return x.Fromid
	}
	return ""
}

func (x *EventData) GetToid() string {
	if x != nil {
		return x.Toid
	}
	return ""
}

func (x *EventData) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *EventData) GetComplete() string {
	if x != nil {
		return x.Complete
	}
	return ""
}

func (x *EventData) GetPositionbeforebaseload() string {
	if x != nil {
		return x.Positionbeforebaseload
	}
	return ""
}

var File_dataceenevent_proto protoreflect.FileDescriptor

const file_dataceenevent_proto_rawDesc = "" +
	"\n" +
	"\x13dataceenevent.proto\x12\bdataceen\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\x13SubscriptionRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12&\n" +
	"\x0ebaseloadtopics\x18\x04 \x03(\tR\x0ebaseloadtopics\x12\x16\n" +
	"\x06topics\x18\x05 \x03(\tR\x06topics\x12\x10\n" +
	"\x03ids\x18\x06 \x03(\tR\x03ids\x121\n" +
	"\tstartmode\x18\a \x01(\x0e2\x13.dataceen.StartModeR\tstartmode\x12\x1a\n" +
	"\bposition\x18\b \x01(\tR\bposition\x128\n" +
	"\tstarttime\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstarttime\x12\"\n" +
	"\fincludedelta\x18\n" +
	" \x01(\bR\fincludedelta\x12(\n" +
	"\x0fincludecomplete\x18\v \x01(\bR\x0fincludecomplete\x12>\n" +
	"\x1abaseloadcontinueobjecttype\x18\f \x01(\tR\x1abaseloadcontinueobjecttype\x126\n" +
	"\x16positionbeforebaseload\x18\r \x01(\tR\x16positionbeforebaseload\"\xc8\x04\n" +
	"\tEventData\x127\n" +
	"\vmessagetype\x18\x01 \x01(\x0e2\x15.dataceen.MessageTypeR\vmessagetype\x121\n" +
	"\teventtype\x18\x02 \x01(\x0e2\x13.dataceen.EventTypeR\teventtype\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x128\n" +
	"\teventtime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\teventtime\x124\n" +
	"\n" +
	"objecttype\x18\x05 \x01(\x0e2\x14.dataceen.ObjectTypeR\n" +
	"objecttype\x12=\n" +
	"\roperationtype\x18\x06 \x01(\x0e2\x17.dataceen.OperationTypeR\roperationtype\x12\x1a\n" +
	"\bclientid\x18\a \x01(\tR\bclientid\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x14\n" +
	"\x05topic\x18\n" +
	" \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\v \x01(\tR\x02id\x12\x16\n" +
	"\x06fromid\x18\f \x01(\tR\x06fromid\x12\x12\n" +
	"\x04toid\x18\r \x01(\tR\x04toid\x12\x14\n" +
	"\x05delta\x18\x0e \x01(\tR\x05delta\x12\x1a\n" +
	"\bcomplete\x18\x0f \x01(\tR\bcomplete\x126\n" +
	"\x16positionbeforebaseload\x18\x10 \x01(\tR\x16positionbeforebaseload*j\n" +
	"\tStartMode\x12\x16\n" +
	"\x12POSITION_BEGINNING\x10\x00\x12\x10\n" +
	"\fPOSITION_END\x10\x01\x12\x12\n" +
	"\x0ePOSITION_EXACT\x10\x02\x12\x11\n" +
	"\rPOSITION_TIME\x10\x03\x12\f\n" +
	"\bBASELOAD\x10\x04*(\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\r\n" +
	"\tKEEPALIVE\x10\x01*\xc6\x01\n" +
	"\tEventType\x12\x16\n" +
	"\x12SUBSCRIPTION_EVENT\x10\x00\x12\x12\n" +
	"\x0eBASELOAD_EVENT\x10\x01\x12\x13\n" +
	"\x0fBASELOAD_STEP_1\x10\x02\x12\x17\n" +
	"\x13BASELOAD_STEP_1_ALL\x10\x03\x12\x10\n" +
	"\fBASELOAD_END\x10\x04\x12\x1c\n" +
	"\x18POSITION_AT_START_PASSED\x10\x05\x12\x13\n" +
	"\x0fCONNECTION_LOST\x10\x06\x12\x1a\n" +
	"\x16CONNECTION_RECONNECTED\x10\a*3\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02*(\n" +
	"\n" +
	"ObjectType\x12\b\n" +
	"\x04NODE\x10\x00\x12\x10\n" +
	"\fRELATIONSHIP\x10\x012R\n" +
	"\rDataceenEvent\x12A\n" +
	"\tSubscribe\x12\x1d.dataceen.SubscriptionRequest\x1a\x13.dataceen.EventData0\x01BTZ=github.com/dataceen/client-go/pkg/dataceenevent;dataceenevent\xaa\x02\x12DataceenEventStoreb\x06proto3"

var (
	file_dataceenevent_proto_rawDescOnce sync.Once
	file_dataceenevent_proto_rawDescData []byte
)

func file_dataceenevent_proto_rawDescGZIP() []byte {
	file_dataceenevent_proto_rawDescOnce.Do(func() {
		file_dataceenevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataceenevent_proto_rawDesc), len(file_dataceenevent_proto_rawDesc)))
	})
	return file_dataceenevent_proto_rawDescData
}

var file_dataceenevent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_dataceenevent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dataceenevent_proto_goTypes = []any{
	(StartMode)(0),                // 0: dataceen.StartMode
	(MessageType)(0),              // 1: dataceen.MessageType
	(EventType)(0),                // 2: dataceen.EventType
	(OperationType)(0),            // 3: dataceen.OperationType
	(ObjectType)(0),               // 4: dataceen.ObjectType
	(*SubscriptionRequest)(nil),   // 5: dataceen.SubscriptionRequest
	(*EventData)(nil),             // 6: dataceen.EventData
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_dataceenevent_proto_depIdxs = []int32{
	0, // 0: dataceen.SubscriptionRequest.startmode:type_name -> dataceen.StartMode
	7, // 1: dataceen.SubscriptionRequest.starttime:type_name -> google.protobuf.Timestamp
	1, // 2: dataceen.EventData.messagetype:type_name -> dataceen.MessageType
	2, // 3: dataceen.EventData.eventtype:type_name -> dataceen.EventType
	7, // 4: dataceen.EventData.eventtime:type_name -> google.protobuf.Timestamp
	4, // 5: dataceen.EventData.objecttype:type_name -> dataceen.ObjectType
	3, // 6: dataceen.EventData.operationtype:type_name -> dataceen.OperationType
	5, // 7: dataceen.DataceenEvent.Subscribe:input_type -> dataceen.SubscriptionRequest
	6, // 8: dataceen.DataceenEvent.Subscribe:output_type -> dataceen.EventData
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_dataceenevent_proto_init() }
func file_dataceenevent_proto_init() {
	if File_dataceenevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataceenevent_proto_rawDesc), len(file_dataceenevent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataceenevent_proto_goTypes,
		DependencyIndexes: file_dataceenevent_proto_depIdxs,
		EnumInfos:         file_dataceenevent_proto_enumTypes,
		MessageInfos:      file_dataceenevent_proto_msgTypes,
	}.Build()
	File_dataceenevent_proto = out.File
	file_dataceenevent_proto_goTypes = nil
	file_dataceenevent_proto_depIdxs = nil
}
