package schema

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/dataceen/client-go/pkg/dataceen"
)

// CachePath is the on-disk location for the cached schema, relative to the
// repo root. Gitignored — it's regenerated by `make codegen-schema`.
const CachePath = "tools/codegen/cache/schema.json"

// Fetch posts an IntrospectionQuery to the live Dataceen backend and returns
// a CachedSchema ready to be serialised. Uses the same dataceen.Client + token
// flow that production code does.
func Fetch(ctx context.Context, cfg dataceen.Config) (*CachedSchema, error) {
	client, err := dataceen.NewClient(cfg, dataceen.WithLogger(dataceen.SilentLogger))
	if err != nil {
		return nil, fmt.Errorf("schema.Fetch: NewClient: %w", err)
	}

	var data IntrospectionResponse
	// Introspection responses key data by `__schema` (the GraphQL field name),
	// not by operation name. Use ExecuteRaw which decodes the whole `data`
	// object and lets the IntrospectionResponse json tag pick it up.
	err = client.ExecuteRaw(ctx, dataceen.GraphQL{
		OperationName: "IntrospectionQuery",
		Query:         IntrospectionQuery,
	}, &data)
	if err != nil {
		return nil, fmt.Errorf("schema.Fetch: introspection: %w", err)
	}

	endpoint := fmt.Sprintf("%s%s/%s/%s/%s",
		cfg.APIURL, cfg.APIPath, cfg.Domain, cfg.Model, cfg.Scope)

	byKind := map[string]int{}
	for _, t := range data.Schema.Types {
		byKind[t.Kind]++
	}

	return &CachedSchema{
		Metadata: Metadata{
			FetchedAt: time.Now().UTC().Format(time.RFC3339),
			Endpoint:  endpoint,
			Domain:    cfg.Domain,
			Model:     cfg.Model,
			Scope:     cfg.Scope,
			Stats: SchemaStats{
				TotalTypes: len(data.Schema.Types),
				ByKind:     byKind,
			},
		},
		Data: data,
	}, nil
}

// WriteCache pretty-prints the CachedSchema to path (creating parent dirs).
func WriteCache(path string, cached *CachedSchema) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	buf, err := json.MarshalIndent(cached, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	return os.WriteFile(path, buf, 0o644)
}

// ReadCache loads the cached schema from path. Returns (nil, nil) if absent.
func ReadCache(path string) (*CachedSchema, error) {
	buf, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read: %w", err)
	}
	var cached CachedSchema
	if err := json.Unmarshal(buf, &cached); err != nil {
		return nil, fmt.Errorf("unmarshal %s: %w", path, err)
	}
	return &cached, nil
}
